all:
    gcc test_read_raw.c ../lofasm_data_IO.c  ../lofasmUtils.c ../lofasm_data_read.c ../lofasm_data_type.c ../LOFASM_RAW/lofasm_raw_read.c -o test_raw_read  -I/home/lofasm/lofasm_lib_c/lofasmIO/include
    



